export const MERCHANTS = {
  FETCH_MERCHANTS: 'MERCHANTS/FETCH_MERCHANTS',
  FETCH_MERCHANT: 'MERCHANTS/FETCH_MERCHANT',
  UPDATE_MERCHANT: 'MERCHANTS/UPDATE_MERCHANT',
  DELETE_MERCHANT: 'MERCHANTS/DELETE_MERCHANT',
  ADD_MERCHANT: 'MERCHANTS/ADD_MERCHANT'
};
